use_gpu: true
gpu_id: 0
worker: 0
seed: 2026
reproducibility: True

#model config
model: BPR
embedding_size: 64

# training config
checkpoint_path: './ckptCopy/BPR-beauty-baseline.pth'
pretrain: True
epochs: 1000
learning_rate: 1e-3
stopping_step: 20
train_batch_size: 40960
eval_batch_size: 4096000
loss_decimal_place: 2
eval_step: 1
train_neg_sample_args: 
    distribution: uniform
    sample_num: 1
    alpha: 1
    # dynamic: True
    # candidate_num: 3


# Sampling config
strategy: 'icpns'
finetune: False
finetune_epochs: 500
stopping_step_ft: 20
num_clusters: 64
popularity_alpha: 0.1
epsilon: 0.0001
cluster_method: 'kmeans'
finetune_lr: 1e-3

# evaluation config
metrics: ['Recall', 'MRR', 'NDCG', 'Precision']
eval_setting: RO_RS,full
split_ratio: [0.8, 0.1, 0.1]
topk: [10]
valid_metric: NDCG@10
eval_args:
    mode: full
metric_decimal_place: 3
eval_step: 1

# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id]
val_interval:
    rating: "[3,inf)"
unused_col: 
    inter: [rating]
user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"
save_dataset: True