use_gpu: true
gpu_id: 0
worker: 4
seed: 2026
reproducibility: True

#model config
model: NCL
embedding_size: 64
n_layers: 3
reg_weight: 1e-4
ssl_temp: 0.1
ssl_reg: 1e-7
hyper_layers: 1
alpha: 1
proto_reg: 8e-8
num_clusters: 1000
m_step: 1
warm_up_step: 20

# training config
checkpoint_path: './ckptCopy/lgn-ml100k-baseline.pth'
pretrain: True
epochs: 1000
learning_rate: 1e-3
stopping_step: 20
train_batch_size: 4096
eval_batch_size: 4096000
train_neg_sample_args: 
    distribution: uniform
    sample_num: 1
    # alpha: 0.1
    # dynamic: True
    # candidate_num: 10
loss_decimal_place: 2

# ICPNS config
strategy: icpns
finetune: False
finetune_epochs: 1000
stopping_step_ft: 20
num_clusters: 8
popularity_alpha: 0.1
epsilon: 0.0001
cluster_method: 'kmeans'
finetune_lr: 1e-3

# evaluation config
metrics: ['Recall', 'MRR', 'NDCG', 'Precision']
eval_setting: RO_RS,full
split_ratio: [0.8, 0.1, 0.1]
topk: [10]
valid_metric: NDCG@10
eval_args:
    mode: full
metric_decimal_place: 3
eval_step: 1


# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
val_interval:
    rating: "[3,inf)"

user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"
